# ==========================================
# CONFIGURACION GENERAL
# ==========================================
spring.application.name=btg-funds-service

# ==========================================
# CONFIGURACION DEL SERVIDOR
# ==========================================
server.port=8080
server.servlet.context-path=/api/v1

# Credenciales del usuario btg-notifications-user
aws.accessKeyId=AKIA53LY2BNCBUR2U5O6
aws.secretAccessKey=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
# ==========================================
# CONFIGURACION AWS / DYNAMODB
# ==========================================
aws.region=us-east-1

# ==========================================
# SEGURIDAD JWT
# ==========================================
security.jwt.secret-key=EstaEsUnaClaveSuperSecretaParaBTG2026
security.jwt.expiration-time=3600000

# ==========================================
# CONFIGURACION DE LOGS (Opcional pero util)
# ==========================================
logging.level.org.springframework.web=INFO
# Para ver las peticiones que salen hacia AWS:
logging.level.software.amazon.awssdk=DEBUG

# Credenciales del usuario con politica BTG-DatabaseFullAccess-Policy
aws.dynamodb.accessKey=AKIA53LY2BNCLYA3F6U4
aws.dynamodb.secretKey=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
aws.dynamodb.endpoint=https://dynamodb.us-east-1.amazonaws.com






